[theme]
theme = "solarized-dark"

[icons]
icons = "awesome5"

[[block]]
block = "backlight"
device = "intel_backlight"
cycle = [5, 15, 40, 75, 90]

[[block]]
block = "battery"
interval = 10
full_threshold = 95
full_format = "Full $power"
format = "$icon  $percentage $time"
good = 60
info = 40
warning = 20
critical = 10

[[block]]
block = "cpu"
interval = 1
format = "$icon $utilization"

[[block]]
block = "memory"
format = "$mem_used.eng(prefix:M)/$mem_total.eng(prefix:M)"
interval = 5
warning_mem = 80
warning_swap = 80
critical_mem = 95
critical_swap = 95

[[block]]
block = "sound"
step_width = 2
max_vol = 100

# [[block]]
# block = "toggle"
# text = "ядо"
# command_on = "~/coordinate_transformation_matrix.bash main"
# command_off = "~/coordinate_transformation_matrix.bash"
# command_state = "cat ~/.cache/coordinate_transformation_matrix/state"

[[block]]
block = "time"
format = "$icon $timestamp.datetime(f:'%d/%m', l:de_DE), $timestamp.datetime(f:%R, l:de_DE)"
timezone = "Europe/Berlin"
interval = 60
